In [7]:
import numpy as np
import matplotlib.pyplot as plt 
%matplotlib inline

In [5]:

para = 3
mse_list = np.zeros([para,3])
true = -0.26557
n = 400000

for j in range(3):
    if j!=1:
        aaa = np.load("./un_ver="+str(j+1)+"nt=1ts="+str(n)+"gm=0.98.npy")[:,0:10]
        print aaa
    else:
        aaa = np.load("./un_ver="+str(j+1)+"nt=1ts="+str(n)+"gm=0.98.npy")[:,0:10]
        print aaa
    for i in range(3):
        mse_list[j,i] = np.mean((true-aaa[i,:])*(true-aaa[i,:]))

[[ 0.08588438 -0.21969059 -0.4697488  -0.11169932 -0.39776152 -0.42892256
  -0.36395743  0.09624025 -0.7683372   0.20460667]
 [-0.25353235 -0.2541497  -0.272417   -0.26268843 -0.26530635 -0.25693876
  -0.26864257 -0.27002975 -0.26175034 -0.27206242]
 [-0.25653675 -0.25505412 -0.2657823  -0.2612415  -0.25515476 -0.25881788
  -0.2596945  -0.26509294 -0.26303986 -0.26564297]]
[[-0.25998315 -0.4048006   0.10095242 -0.60788226 -0.4062581  -0.5574121
  -0.13139598 -0.38549444 -0.73662376 -0.10027832]
 [-0.26032776 -0.26158923 -0.26266244 -0.26426297 -0.2544173  -0.2630406
  -0.2545614  -0.2608959  -0.2651456  -0.25470063]
 [-0.25937733 -0.25557107 -0.2575765  -0.25651854 -0.26084185 -0.25922218
  -0.25686905 -0.25737876 -0.25882703 -0.25796536]]
[[-0.59820807 -0.4691731  -0.45009145 -0.42425734  0.08089311 -0.24280919
  -0.20353837 -0.16618243 -0.26234365 -0.2914215 ]
 [-0.25649068 -0.2647676  -0.25277123 -0.2613527  -0.2533004  -0.26070154
  -0.26468003 -0.26417944 -0.26144034 -0.2550234 ]


In [6]:
print mse_list
print np.log10(np.mean(mse_list,0))

[[8.49576741e-02 4.91152969e-05 4.06190447e-05]
 [6.57495186e-02 4.45631849e-05 5.92906545e-05]
 [3.46291363e-02 5.69929834e-05 4.86782264e-05]]
[-1.2091607  -4.29909024 -4.30513773]
